# Generated by Django 5.1.5 on 2025-02-11 14:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_transaction_date_transaction_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Expenses',
        ),
    ]
