# Generated by Django 5.1.5 on 2025-02-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expenses_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
