# Generated by Django 5.1.5 on 2025-02-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_expenses_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
