# Generated by Django 5.1.5 on 2025-02-23 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_expenses_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 23, 10, 55, 23, 725117, tzinfo=datetime.timezone.utc)),
        ),
    ]
