# Generated by Django 5.1.5 on 2026-01-12 15:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_expenses',
            name='category',
        ),
        migrations.RemoveField(
            model_name='group_expense_comments',
            name='group_expense',
        ),
        migrations.RemoveField(
            model_name='group_expense_comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='group_expense_participants',
            name='group_expense',
        ),
        migrations.RemoveField(
            model_name='group_expense_participants',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='group_expense_settlements',
            name='group',
        ),
        migrations.RemoveField(
            model_name='group_expense_settlements',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='group_expense_settlements',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='group_expenses',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='group_expenses',
            name='group',
        ),
        migrations.RemoveField(
            model_name='group_expenses',
            name='paid_by',
        ),
        migrations.CreateModel(
            name='GroupExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='groups.groups')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_expenses_paid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_splits', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='groups.groupexpense')),
            ],
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='group_expense_comments',
        ),
        migrations.DeleteModel(
            name='group_expense_participants',
        ),
        migrations.DeleteModel(
            name='group_expense_settlements',
        ),
        migrations.DeleteModel(
            name='group_expenses',
        ),
    ]
