# Generated by Django 5.1.5 on 2026-01-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groupexpense_paid_by_expensepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupexpense',
            name='deleted',
        ),
        migrations.AddField(
            model_name='groupexpense',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('INR', 'INR (₹)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)')], default='USD', max_length=3),
        ),
    ]
