# Generated by Django 5.1.5 on 2026-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_remove_groupexpense_deleted_groupexpense_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupexpense',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
