# Generated by Django 5.1.5 on 2026-01-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_groupexpense_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensepayment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
