# Generated by Django 5.1.5 on 2026-01-12 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_remove_expensesplit_paid_remove_groups_updated_at_and_more'),
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groupinvitation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GROUP_ADD', 'Added to Group'), ('INVITATION', 'Group Invitation'), ('EXPENSE_ADD', 'New Expense Added'), ('SETTLEMENT', 'Debt Settled'), ('SYSTEM', 'System Notification')], max_length=20),
        ),
    ]
