# Generated by Django 5.1.5 on 2026-01-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_invitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GROUP_ADD', 'Added to Group'), ('INVITATION', 'Group Invitation'), ('EXPENSE_ADD', 'New Expense Added'), ('SETTLEMENT', 'Debt Settled'), ('SYSTEM', 'System Notification')], default='SYSTEM', max_length=20),
        ),
    ]
